version: '3.8'

services:
  nats:
    image: nats:2.0.0
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    command:
      - "-DV"
    networks:
      - lan
    restart: always

  microservice_builder:
    image: microservice_builder:latest
    container_name: microservice_builder
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nats

  service1:
    image: service1:latest
    container_name: service1
    ports:
      - "50000:50000"
    environment:
      - MICRO_SERVER_ADDRESS=:50000
    build:
      context: .
      dockerfile: ./service1/Dockerfile
    depends_on:
      - microservice_builder
    networks:
      - lan

  service2:
    image: service2:latest
    container_name: service2
    ports:
      - "50001:50001"
    environment:
      - MICRO_SERVER_ADDRESS=:50001
      - MICRO_BROKER=nats
      - MICRO_BROKER_ADDRESS=nats:4222
      - LATENCY_SEC=10
      - TOPIC_NAME=messages
    build:
      context: .
      dockerfile: ./service2/Dockerfile
    depends_on:
      - microservice_builder
    networks:
      - lan

  service3:
    image: service3:latest
    container_name: service3
    ports:
      - "50002:50002"
    environment:
      - MICRO_SERVER_ADDRESS=:50002
      - MICRO_BROKER=nats
      - MICRO_BROKER_ADDRESS=nats:4222
      - TOPIC_NAME=messages
      - SQLITE_DATABASE=database.db
    build:
      context: .
      dockerfile: ./service3/Dockerfile
    depends_on:
      - microservice_builder
    networks:
      - lan

networks:
  lan:
    driver: bridge