// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/service3/service3.proto

package go_micro_service_service3

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Service3 service

func NewService3Endpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Service3 service

type Service3Service interface {
	Telemetry(ctx context.Context, in *SerialNum, opts ...client.CallOption) (*Response, error)
}

type service3Service struct {
	c    client.Client
	name string
}

func NewService3Service(name string, c client.Client) Service3Service {
	return &service3Service{
		c:    c,
		name: name,
	}
}

func (c *service3Service) Telemetry(ctx context.Context, in *SerialNum, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Service3.Telemetry", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service3 service

type Service3Handler interface {
	Telemetry(context.Context, *SerialNum, *Response) error
}

func RegisterService3Handler(s server.Server, hdlr Service3Handler, opts ...server.HandlerOption) error {
	type service3 interface {
		Telemetry(ctx context.Context, in *SerialNum, out *Response) error
	}
	type Service3 struct {
		service3
	}
	h := &service3Handler{hdlr}
	return s.Handle(s.NewHandler(&Service3{h}, opts...))
}

type service3Handler struct {
	Service3Handler
}

func (h *service3Handler) Telemetry(ctx context.Context, in *SerialNum, out *Response) error {
	return h.Service3Handler.Telemetry(ctx, in, out)
}
